#Spring cloud\u6709\u4E24\u79CD\u670D\u52A1\u8C03\u7528\u65B9\u5F0F\uFF0C\u4E00\u79CD\u662Fribbon+restTemplate\uFF0C\u53E6\u4E00\u79CD\u662Ffeign\u3002\u6D88\u8D39\u8005
server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: service-ribbon